# MongoDB Configuracion
spring.data.mongodb.uri=mongodb://localhost:27017/eventhive
spring.data.mongodb.database=eventhive
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.org.springframework.data.mongodb=INFO
logging.level.org.mongodb.driver=INFO