# MongoDB Configuracion
spring.data.mongodb.uri=mongodb://localhost:27017/eventHive
spring.data.mongodb.database=eventHive
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.org.springframework.data.mongodb=INFO
logging.level.org.mongodb.driver=INFO